program/src/admin_update_weight_table.rs
I think `ncn_weight_table_admin` should be `ncn.weight_table_admin`
=> Tip Router: Change `ncn.admin` to `ncn_weight_table_admin`

clients/js/jito_tip_router/errors/jitoTipRouter.ts, clients/js/jito_tip_router/instructions/adminSetParameters.ts, clients/js/jito_tip_router/instructions/index.ts, clients/js/jito_tip_router/programs/jitoTipRouter.ts, clients/rust/jito_tip_router/src/generated/errors/jito_tip_router.rs, clients/rust/jito_tip_router/src/generated/instructions/admin_set_parameters.rs, clients/rust/jito_tip_router/src/generated/instructions/mod.rs, core/src/constants.rs, core/src/error.rs, core/src/instruction.rs, core/src/ncn_config.rs, idl/jito_tip_router.json, integration_tests/tests/fixtures/tip_router_client.rs, integration_tests/tests/tip_router/admin_set_parameters.rs, integration_tests/tests/tip_router/initialize_ncn_config.rs, integration_tests/tests/tip_router/mod.rs, program/src/admin_set_parameters.rs, program/src/initialize_ncn_config.rs, program/src/lib.rs
New instruction to set parameters epochs_before_stall, which indicates how long we wait for consensus to be reached before tie breaking, and valid_slots_after_consensus which is how many slots operators can still vote after consensus has been reached.
Also ensures these parameters are set upon NcnConfig initialization.
Creates valid bounds for these parameters -- double check these are reasonable.
=> AdminSetParameters instruction

clients/js/jito_tip_router/accounts/baseRewardRouter.ts, clients/rust/jito_tip_router/src/generated/accounts/base_reward_router.rs, core/src/base_reward_router.rs, core/src/utils.rs, idl/jito_tip_router.json
There was an issue in the BaseRewardRouter where if max_iterations was hit, it would not carry over the `rewards_to_process` meaning when the instruction ran again, it would go off of the new pre-routed value.
Say we had 10 operators and 5 max_iterations with 10_000 rewards to split:
```
op0: 1000
op1: 1000
op2: 1000
op3: 1000
- Iterations Hit -
op4: 600
op5: 600
op6: 600
op7: 600
op8: 600
op9: 600
```
The fix was to save the `last_rewards_to_process` like we do in route_ncn_rewards;
=> BUG: Fixed interruption in route_base_rewards

cli/src/instructions.rs, clients/js/jito_tip_router/instructions/registerVault.ts, clients/rust/jito_tip_router/src/generated/instructions/register_vault.rs, core/src/instruction.rs, idl/jito_tip_router.json, integration_tests/tests/fixtures/test_builder.rs, integration_tests/tests/fixtures/tip_router_client.rs, integration_tests/tests/tip_router/register_vault.rs, program/src/register_vault.rs, program/src/snapshot_vault_operator_delegation.rs
We just need to know if NcnVaultTicket exists to register the ticket. 
When we take vault operator delegation, we check the state of both NcnVaultTicket and VaultNcnTicket
=> AUDIT: Inconsistent NCN Vault Count

program/src/admin_set_new_admin.rs
Discriminator check has done already by `NcnConfig::load(...)`. So i think we can remove it.
=> Fix: Remove discriminator check

program/src/realloc_operator_snapshot.rs, program/src/snapshot_vault_operator_delegation.rs
- When the NCN makes a ticket invalid - it should take effect immediately 
- When the operator or vault makes a ticket invalid - it can still participate until it is cooled down
=> AUDIT: Update when tickets are considered active

clients/js/jito_tip_router/errors/jitoTipRouter.ts, clients/rust/jito_tip_router/src/generated/errors/jito_tip_router.rs, core/src/error.rs, idl/jito_tip_router.json, integration_tests/tests/tip_router/initialize_operator_snapshot.rs, program/src/initialize_operator_snapshot.rs
Operator Snapshot cannot be initialized if the `ncn_operator_state`'s index is >= `epoch_snapshot`'s operator count.
This would happen if the NCN added the operator after the Epoch Snapshot has been taken and the Operator count has been set
=> AUDIT: Operator Index

core/src/base_reward_router.rs, core/src/ncn_reward_router.rs, integration_tests/tests/fixtures/test_builder.rs, integration_tests/tests/tip_router/distribute_rewards.rs
+ Rounding Error is fixed
Before, when we would call the following, it would double count for the `leftover_rewards` in `rewards_processed`
```rust
// DAO gets any remainder
{
let leftover_rewards = self.ncn_fee_group_rewards(group)?;
self.route_from_ncn_fee_group_rewards(group, leftover_rewards)?;
self.route_to_base_fee_group_rewards(BaseFeeGroup::dao(), leftover_rewards)?;
}
```
This is because we increment `rewards_processed` when we route to the `ncn_fee_group_rewards` or `base_fee_group_rewards`, however in the example above, we routed to ncn, counted and then routed to base, counted.
The fix is to increment `rewards_processed` only when we route from the reward pool. ( Note, `rewards_processed` is only decremented on the distribute functions )
This has also been changed in …
=> FIX: Rounding Error

core/src/epoch_snapshot.rs
Reverts the changes of PR #46 ( actually merged in PR #47 )
This issue this meant to address, upon further investigation, was not an issue.
=> REVERT: Use `total_security`

meta_merkle_tree/src/generated_merkle_tree.rs
Aligns tip router validator distributions with the original MEV claim process, see original validator claimant here: https://github.com/jito-foundation/jito-tip-router/pull/100#issue-2911328632
Target epoch is 756, meaning operators will generate a merkle root for this at the start of epoch 757 (Rolls over Monday night UTC 3/17)
=> Switch to vote account claimants epoch 756

cli/src/getters.rs, cli/src/instructions.rs
- Back to using all operators, this is because an operator still needs to be tallied, even if its no longer active.
=> FIX: Now crank with all operators

.github/workflows/ci.yaml, cli/src/args.rs, cli/src/handler.rs, cli/src/keeper/keeper_loop.rs, docker-compose.yaml
**Problem**
We would like to scale up our keeper instances for redundancy purposes but lack the necessary changes to differentiate between replicas of a service from a metrics perspective.
**Solution**
- Use the `HOSTNAME` env var as a component of the `solana_metrics` `host_id` to differentiate between replicas in our monitoring systems
- Ignore RUSTSEC-2025-0022 as this is a brand new vulnerability from transitive deps and will be addressed or ignored upstream
**Local Run Log Output**
See `solana_metrics::metrics host id`
```
[2025-04-07T23:10:57Z INFO  stakenet_keeper] Stakenet Keeper Configuration:
-------------------------------
JSON RPC URL: INCLUDE YOUR RPC URL HERE
Gossip Entrypoint: None
Keypair Path: "./credentials/keypair.json"
Oracle Authority Keypair Path: …
```
=> Keeper: use hostname/container id in metrics host id

gcp_uploader/monitor-merkle-uploads.service
**Problem**
The monitor merkle uploads service config file has drifted from the required arguments of the underlying service.
**Solution**
- Correct the path of the executable
- Add `snapshot-directory` arg with value `/solana/snapshots/autosnapshot`
=> gcp_uploader: Update monitor merkle uploads service

cli/src/keeper/keeper_loop.rs, cli/src/keeper/keeper_metrics.rs, tip-router-operator-cli/src/claim.rs, tip-router-operator-cli/src/cli.rs, tip-router-operator-cli/src/ledger_utils.rs, tip-router-operator-cli/src/lib.rs, tip-router-operator-cli/src/load_and_process_ledger.rs, tip-router-operator-cli/src/main.rs, tip-router-operator-cli/src/process_epoch.rs, tip-router-operator-cli/src/submit.rs
**Problem**
We would like to differentiate between instances of tip-router-operator running in against different clusters within our metrics yet lack the ability to do so.
**Solution**
- Differentiate between hosts within the same region/cluster by creating the host_id as "{service_name}_{cluster}_{region}_{hostname}"
- Wire the `cluster` of the operator into the emitted metrics as a tag
=> operator: Emit cluster tag in metrics

.gitmodules, Cargo.lock, tip-router-operator-cli/Cargo.toml, tip-router-operator-cli/src/main.rs
* Relies on a submodule for using the legacy process_epoch code
=> fix: Handle case where old logic should be used prior to start epoch

tip-router-operator-cli/src/tip_router.rs
**Problem**
Tip router operator performs process_transaction which returns as an `Ok` when the transaction is successfully submitted to the validator with no regard for commitment and confirmation. As a result, `cast_vote` metrics do not reflect the actual success rate of the operation.
**Solution**
- Use the `send_and_confirm_transaction` function in `cast_vote` to get the function's return value 
- Existing calling logic will correctly report votes that fail to land
=> operator: confirm cast_vote transactions

tip-router-operator-cli/src/main.rs
**Problem**
There is a scenario where our alerts are falsely suggesting operator downtime due to the logic surrounding metrics emit calls.
**Solution**
- Emit a heartbeat metric in its own periodic looping tokio task
=> operator: emit heartbeats without blocking steps

tip-router-operator-cli/src/process_epoch.rs
* Removes an extra _get_epoch_info_ request. When using a load balanced RPC this could cause potential issues in the stages loop if the subsequent request hit a node that returned the previous epoch informaiton.
=> fix: remove extra get_epoch_info call

integration_tests/tests/tip_router/bpf/set_merkle_root.rs, meta_merkle_tree/src/meta_merkle_tree.rs, tip-router-operator-cli/src/main.rs, tip-router-operator-cli/src/tip_router.rs
Noticed 3 TDAs with zero tips that caused a panic because their nodes did not exist in the MetaMerkleTree, and all three had zero tips. Patching to ensure we can set merkle roots and kick off claims.
Nodes:
```
Claimant not found in tree: J8ub95fqxUZbEjLFurVMUMN9wfAHHgbTh84bhkopRJse
[2025-06-05T19:46:53Z ERROR tip_router_operator_cli::tip_router] No node found for tip distribution account J8ub95fqxUZbEjLFurVMUMN9wfAHHgbTh84bhkopRJse
Claimant not found in tree: DGy6Tj63soeNqfKao3Y2cNT5EJKacqLwA8SERoXGDptQ
[2025-06-05T19:46:53Z ERROR tip_router_operator_cli::tip_router] No node found for tip distribution account DGy6Tj63soeNqfKao3Y2cNT5EJKacqLwA8SERoXGDptQ
Claimant not found in tree: H195qWWwZbBub3ehWcUsZdfvhEusvtTTRj2Wz2C44hZR
[2025-06-05T19:46:53Z ERROR …
```
=> Don't panic on missing node

Cargo.lock, tip-router-operator-cli/Cargo.toml
This change upgrades the version of tip-router-operator-cli from 1.2.0 to 1.3.0
- Improved handling of claimant not found in merkle tree
- Upgrade solana related dependencies to 2.2
- Remove ellipsis client dependency
- Ensure the local validator is caught up before loading bank from snapshot
- Improved solana metrics: cast_vote txns should correctly report errors, periodic heartbeat emit, cluster tag
- print-tx flag for displaying transaction information from the CLI
- Addition of `CLUSTER` and `REGION` env vars for more granular metrics
- The keeper will no longer try to create, uncreatable NcnRewardRouters
- Support for additional filename patterns within gcp_uploader
=> tip-router-operator-cli: bump version to 1.3.0

.gitmodules, Cargo.lock, meta_merkle_tree/Cargo.toml, meta_merkle_tree/src/generated_merkle_tree.rs, tip-router-operator-cli/Cargo.toml, tip-router-operator-cli/src/claim.rs, tip-router-operator-cli/src/cli.rs, tip-router-operator-cli/src/lib.rs, tip-router-operator-cli/src/main.rs, tip-router-operator-cli/src/process_epoch.rs
**Problem**
Go-live epoch conditional fallback logic was removed in a recent merge into priority-fee-distribution-support
**Solution**
- Re-introduce loop_stages legacy fallback logic to be executed before the go-live epoch
- Use branch v.1.3.0-legacy for the legacy_tip_router_operator_cli submodule
=> fix: operator loop_stages legacy fallback

cli/src/handler.rs
**Problem**
- Keypair path logic fails in our current tip-router-cli keeper dockerized build due to lack of solana config within container
- Keypair path argument is never read if there is no Solana config at the expected default path
**Solution**
- If Solana config file exists: use keypair path
- If Solana config does not exist: use keypair path argument
=> keeper: modify keypair path / config logic for containerized builds

meta_merkle_tree/src/generated_merkle_tree.rs, tip-router-operator-cli/src/claim.rs
**Problem**
The amount to pay out to vote account claimants is not calculated correctly when total_fees exceed total_tips. This scenario manifests when validator commission bps on tip distributions is set to 10_000.
**Solution**
- Subtract protocol fees from vote account claimant payouts when total fees exceed total tips
- Test case for 10_000 bps commission on tip distribution
- Test case for legacy calculation (feature gated at epoch 815)
=> fix: claims logic when total_fees are greater than total_tips

Cargo.lock, Cargo.toml, tip-router-operator-cli/Cargo.toml, tip-router-operator-cli/src/load_and_process_ledger.rs
**Problem**
Solana 2.3 deps introduce a rocksdb version upgrade from `0.22` => `0.23`. We have observed that this particular upgrade introduces a massive performance regression while opening the blockstore with the required `Secondary` access type.
**Solution**
- Point to jito-solana gzalz/v2.3 which downgrades rocksdb to 0.22
- Don't block on joining with the accounts background service, we have observed failures in production with 2.3 dependencies
=> fix: address blockstore open performance regression

cli/Dockerfile
- To do health check of NCN Keeper on remote machine, we need to install `procps` library
=> CI/CD: Add procps

.github/workflows/build-container-images.yaml
- Took time to build and publish image of ncn-keeper
- Changes the runner from `ubuntu-latest` to `big-runner-1` for the build-container job
=> CI/CD: Change to `big-runner-1`
